services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://:redis@redis:6379
    volumes:
      - ./packages/api:/app/packages/api
      - ./data:/app/packages/api/data
      - /app/node_modules
      - /app/packages/api/node_modules
      - /app/packages/web/node_modules
    command: lerna run dev --scope=@otoge.app/api
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REACT_APP_GOOGLE_MAPS_API_KEY=AIzaSyBQzjeZMmOMg3_oEaKf1Ef2q80QgXwKbWk
      - REACT_APP_API_BASE_URL=http://localhost:3000
    volumes:
      - ./packages/web:/app/packages/web
      - /app/node_modules
      - /app/packages/api/node_modules
      - /app/packages/web/node_modules
    command: lerna run dev --scope=@otoge.app/web
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--requirepass redis
