enum GameEnum {
  HATSUNE_MIKU_PROJECT_DIVA_ARCADE = "HATSUNE_MIKU_PROJECT_DIVA_ARCADE",
  MAIMAI = "MAIMAI",
  MAIMAI_DX = "MAIMAI_DX",
  MAIMAI_DX_INTERNATIONAL = "MAIMAI_DX_INTERNATIONAL",
  CHUNITHM = "CHUNITHM",
  CHUNITHM_NEW = "CHUNITHM_NEW",
  CHUNITHM_NEW_INTERNATIONAL = "CHUNITHM_NEW_INTERNATIONAL",
  ONGEKI = "ONGEKI",
}

export default GameEnum
